import React from "react";

export default class Buttons extends React.Component {
  render() {
    return (
      <div className="keys">
        <button
          className="jumbo"
          id="clear"
          onClick={this.props.initialize}
          value="AC"
        >
          AC
        </button>
        <button
          id="divide"
          onClick={this.props.operators}
          className="operator"
          value="/"
        >
          /
        </button>
        <button
          id="multiply"
          onClick={this.props.operators}
          className="operator"
          value="x"
        >
          x
        </button>
        <button
          id="seven"
          onClick={this.props.numbers}
          value="7"
          className="row-one"
        >
          7
        </button>
        <button
          id="eight"
          onClick={this.props.numbers}
          value="8"
          className="row-one"
        >
          8
        </button>
        <button
          id="nine"
          onClick={this.props.numbers}
          value="9"
          className="row-one"
        >
          9
        </button>
        <button
          id="subtract"
          onClick={this.props.operators}
          className="operator"
          value="‑"
        >
          -
        </button>
        <button
          id="four"
          onClick={this.props.numbers}
          value="4"
          className="row-two"
        >
          4
        </button>
        <button
          id="five"
          onClick={this.props.numbers}
          value="5"
          className="row-two"
        >
          5
        </button>
        <button
          id="six"
          onClick={this.props.numbers}
          value="6"
          className="row-two"
        >
          6
        </button>
        <button
          id="add"
          onClick={this.props.operators}
          className="operator"
          value="+"
        >
          +
        </button>
        <button
          id="one"
          onClick={this.props.numbers}
          value="1"
          className="row-three"
        >
          1
        </button>
        <button
          id="two"
          onClick={this.props.numbers}
          value="2"
          className="row-three"
        >
          2
        </button>
        <button
          id="three"
          onClick={this.props.numbers}
          value="3"
          className="row-three"
        >
          3
        </button>
        <button
          className="jumbo"
          id="zero"
          onClick={this.props.numbers}
          value="0"
        >
          0
        </button>
        <button id="decimal" onClick={this.props.decimal} value=".">
          .
        </button>
        <button id="equals" onClick={this.props.evaluate} value="=">
          =
        </button>
      </div>
    );
  }
}
